[package]
name = "storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
shared = { workspace = true }

sqlx = { workspace = true }
snafu = { workspace = true }
tracing = { workspace = true }
ulid = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
base64 = { workspace = true }
parking_lot = { workspace = true }

[lints]
workspace = true
