[package]
name = "plugin"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
shared = { workspace = true }

reqwest = { workspace = true, features = ["json", "query"] }
serde = { workspace = true }
serde_json = { workspace = true }
graphql_client = { workspace = true }
snafu = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
dotenvy = "0.15"
test-log = {version = "0.2", default-features = false, features = ["trace"]}
tokio = { workspace = true }

[lints]
workspace = true
